services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && echo 'server { listen 80; location / { proxy_pass http://web:3000; } }' > /etc/nginx/conf.d/tareas.conf && nginx -g 'daemon off;'"
    depends_on:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    deploy:
      replicas: 3